name: autotag

on:
  push:
    branches:
      - main
      - master
    tags-ignore:
      - '*'

jobs:
  auto-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: ArvindSinghRawat/Automatic-Semantic-versioning-semver-Tagging@main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}